name: test
on:
  push:
jobs:
  test:
    name: Release Test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: test
        id: git_describe
        run: git describe

      - name: build
        run: .\test.bat

