name: test
on:
  push:
jobs:
  test:
    name: Release Test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: test
        run: .\test.bat ${{ github.ref.replace(/refs\/tags\//, '') }}

      - name: if_tag
        if: contains(github.ref, 'tags/v')
        run: .\test.bat have_tag

      - name: test2
        run: .\test.bat
